# =================================================================
# INWENTARZ INFRASTRUKTURY ANSIBLE
# =================================================================

[ubuntu_server]
# Używamy aliasu 'ubuntu', ponieważ jest on zdefiniowany w ~/.ssh/config.
# Dzięki temu nie musimy wpisywać tutaj adresu IP, portu ani użytkownika.
# Ansible automatycznie pobierze te dane z konfiguracji SSH systemu.
ubuntu ansible_python_interpreter=/usr/bin/python3 ansible_user=Mariusz ansible_host=192.168.56.11 ansible_port=2222

[almalinux]
# Alias 'alma' również pochodzi z ~/.ssh/config.
# 'ansible_connection=local' mówi Ansible, że to jest maszyna, 
# na której aktualnie pracujemy (localhost), więc nie musi 
# łączyć się z nią przez sieć, tylko może działać bezpośrednio.
alma ansible_connection=local

[wsl]
#jeśli uruchamiasz z Almy i chcesz uderzyć do WSL przez SSH:
wsl ansible_host=127.0.0.1 ansible_port=4444 ansible_user=mariusz ansible_python_interpreter=/usr/bin/python3

# =================================================================
# NOTATKI DLA ADMINISTRATORA:
# 1. Jeśli zmieni się IP serwera, edytuj plik ~/.ssh/config na Almie.
# 2. Jeśli dodasz nowy serwer, dopisz go tutaj pod nową grupą.
# 3. Parametr ansible_python_interpreter zapobiega ostrzeżeniom 
#    o niejednoznaczności wersji Pythona na Ubuntu.
# =================================================================
