---
- name: "Deploy Monitoring (Netdata) - bezpośrednio na Ubuntu Server"
  hosts: ubuntu_server
  become: yes         # Globalny root dla zadań systemowych i wolumenów
  vars_files:
    - ../vars/secrets.yml

  vars:
    project_name: "monitoring"
    project_repo: "git@github.com:mariuszhoxton/monitoring-project.git"
    project_path: "/home/{{ ansible_user }}/projects/{{ project_name }}"
    global_net_name: "global_monitoring_net"

  tasks:
    - name: "1. Tworzenie folderu projektu na Ubuntu"
      ansible.builtin.file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: "2. Pobieranie kodu monitoringu z GitHuba"
      ansible.builtin.git:
        repo: "{{ project_repo }}"
        dest: "{{ project_path }}"
        version: main
        force: yes
        accept_hostkey: yes
      become: no  # Pobieranie jako Mariusz dla kluczy SSH

    - name: "3. Bezpieczne zatrzymanie i wyczyszczenie starych zasobów Netdata"
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: absent
      failed_when: false # Ignoruje błąd, jeśli to pierwszy start systemu

    - name: "4. Uruchomienie Netdata przez Docker Compose"
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: present
        pull: missing # Pobiera obraz tylko wtedy, gdy go nie ma na dysku
