---
- name: Deploy aplikacji z GitHub bezpośrednio na Ubuntu (z Nginx)
  hosts: ubuntu_server
  become: yes
  vars_files:
    - ../vars/secrets.yml
  vars:
    project_name: "moj-sklep"
    project_repo: "git@github.com:mariuszhoxton/shop-project.git"
    project_path: "/home/{{ ansible_user }}/projects/{{ project_name }}"

  tasks:
    - name: "Upewnij się, że katalog projektów istnieje"
      file:
        path: "/home/{{ ansible_user }}/projects"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755' 

    - name: "Pobierz/Aktualizuj kod projektu z GitHub"
      git:
        repo: "{{ project_repo }}"
        dest: "{{ project_path }}"
        version: main
        accept_hostkey: yes
        force: yes 
      become: no

    - name: "Wymuś stworzenie konfiguracji Nginx (Obejście błędu Git)"
      copy:
        dest: "{{ project_path }}/nginx/conf.d/default.conf"
        content: |
          server {
              listen 80;
              server_name localhost;
              location / {
                  proxy_pass http://wordpress:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
  

    # To zadanie jest ważne, bo Nginx potrzebuje folderu conf.d przed startem
    - name: "Upewnij się, że struktura katalogów Nginx istnieje"
      file:
        path: "{{ project_path }}/nginx/conf.d"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: "Stworz plik .env z haslami z Vault"
      template:
        src: "../templates/.env.j2"
        dest: "{{ project_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: "Uruchom projekt przez Docker Compose (NGINX + WP + DB)"
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: present
        # Dodajemy pull, aby Docker zawsze sprawdził czy nie ma nowszych obrazów
        pull: always 
