---
- name: "Deploy Monitoring (Netdata) - bezpośrednio na Ubuntu Server"
  hosts: ubuntu_server
  gather_facts: no  # Wyłączamy zbieranie faktów jako root (zapobiega Permission Denied)
  become: no        # Łączymy się dokładnie tak samo jak Twoje ręczne 'ssh ubuntu'

  vars:
    # Wpisujemy ścieżkę na sztywno, ponieważ wyłączyliśmy automatyczne zbieranie zmiennych ansible_env
    project_path: "/home/Mariusz/projects/monitoring"
    project_repo: "git@github.com:mariuszhoxton/monitoring-project.git" 

  tasks:
    - name: "1. Tworzenie folderu projektu na Ubuntu"
      ansible.builtin.file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: "2. Pobieranie kodu monitoringu z GitHuba na Ubuntu"
      ansible.builtin.git:
        repo: "{{ project_repo }}"
        dest: "{{ project_path }}"
        version: main
        force: yes

    - name: "3. Uruchomienie Netdata przez Docker Compose"
      ansible.builtin.shell:
        cmd: "docker compose up -d"
        chdir: "{{ project_path }}"
